// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: verge/v1/branches.proto

package vergev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Branch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	RepoId        string                 `protobuf:"bytes,2,opt,name=repo_id,json=repoId,proto3" json:"repo_id,omitempty"`
	CommitId      string                 `protobuf:"bytes,3,opt,name=commit_id,json=commitId,proto3" json:"commit_id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // ISO 8601
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Branch) Reset() {
	*x = Branch{}
	mi := &file_verge_v1_branches_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Branch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Branch) ProtoMessage() {}

func (x *Branch) ProtoReflect() protoreflect.Message {
	mi := &file_verge_v1_branches_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Branch.ProtoReflect.Descriptor instead.
func (*Branch) Descriptor() ([]byte, []int) {
	return file_verge_v1_branches_proto_rawDescGZIP(), []int{0}
}

func (x *Branch) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Branch) GetRepoId() string {
	if x != nil {
		return x.RepoId
	}
	return ""
}

func (x *Branch) GetCommitId() string {
	if x != nil {
		return x.CommitId
	}
	return ""
}

func (x *Branch) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type CreateBranchRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RepoId         string                 `protobuf:"bytes,1,opt,name=repo_id,json=repoId,proto3" json:"repo_id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	SourceCommitId string                 `protobuf:"bytes,3,opt,name=source_commit_id,json=sourceCommitId,proto3" json:"source_commit_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateBranchRequest) Reset() {
	*x = CreateBranchRequest{}
	mi := &file_verge_v1_branches_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBranchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBranchRequest) ProtoMessage() {}

func (x *CreateBranchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_verge_v1_branches_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBranchRequest.ProtoReflect.Descriptor instead.
func (*CreateBranchRequest) Descriptor() ([]byte, []int) {
	return file_verge_v1_branches_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBranchRequest) GetRepoId() string {
	if x != nil {
		return x.RepoId
	}
	return ""
}

func (x *CreateBranchRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateBranchRequest) GetSourceCommitId() string {
	if x != nil {
		return x.SourceCommitId
	}
	return ""
}

type GetBranchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepoId        string                 `protobuf:"bytes,1,opt,name=repo_id,json=repoId,proto3" json:"repo_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBranchRequest) Reset() {
	*x = GetBranchRequest{}
	mi := &file_verge_v1_branches_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBranchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBranchRequest) ProtoMessage() {}

func (x *GetBranchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_verge_v1_branches_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBranchRequest.ProtoReflect.Descriptor instead.
func (*GetBranchRequest) Descriptor() ([]byte, []int) {
	return file_verge_v1_branches_proto_rawDescGZIP(), []int{2}
}

func (x *GetBranchRequest) GetRepoId() string {
	if x != nil {
		return x.RepoId
	}
	return ""
}

func (x *GetBranchRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListBranchesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepoId        string                 `protobuf:"bytes,1,opt,name=repo_id,json=repoId,proto3" json:"repo_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        string                 `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBranchesRequest) Reset() {
	*x = ListBranchesRequest{}
	mi := &file_verge_v1_branches_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBranchesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBranchesRequest) ProtoMessage() {}

func (x *ListBranchesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_verge_v1_branches_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBranchesRequest.ProtoReflect.Descriptor instead.
func (*ListBranchesRequest) Descriptor() ([]byte, []int) {
	return file_verge_v1_branches_proto_rawDescGZIP(), []int{3}
}

func (x *ListBranchesRequest) GetRepoId() string {
	if x != nil {
		return x.RepoId
	}
	return ""
}

func (x *ListBranchesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListBranchesRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type ListBranchesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Branches      []*Branch              `protobuf:"bytes,1,rep,name=branches,proto3" json:"branches,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBranchesResponse) Reset() {
	*x = ListBranchesResponse{}
	mi := &file_verge_v1_branches_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBranchesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBranchesResponse) ProtoMessage() {}

func (x *ListBranchesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_verge_v1_branches_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBranchesResponse.ProtoReflect.Descriptor instead.
func (*ListBranchesResponse) Descriptor() ([]byte, []int) {
	return file_verge_v1_branches_proto_rawDescGZIP(), []int{4}
}

func (x *ListBranchesResponse) GetBranches() []*Branch {
	if x != nil {
		return x.Branches
	}
	return nil
}

func (x *ListBranchesResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

type AdvanceBranchRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RepoId           string                 `protobuf:"bytes,1,opt,name=repo_id,json=repoId,proto3" json:"repo_id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CommitId         string                 `protobuf:"bytes,3,opt,name=commit_id,json=commitId,proto3" json:"commit_id,omitempty"`
	ExpectedCommitId string                 `protobuf:"bytes,4,opt,name=expected_commit_id,json=expectedCommitId,proto3" json:"expected_commit_id,omitempty"` // required - optimistic lock
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AdvanceBranchRequest) Reset() {
	*x = AdvanceBranchRequest{}
	mi := &file_verge_v1_branches_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdvanceBranchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdvanceBranchRequest) ProtoMessage() {}

func (x *AdvanceBranchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_verge_v1_branches_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdvanceBranchRequest.ProtoReflect.Descriptor instead.
func (*AdvanceBranchRequest) Descriptor() ([]byte, []int) {
	return file_verge_v1_branches_proto_rawDescGZIP(), []int{5}
}

func (x *AdvanceBranchRequest) GetRepoId() string {
	if x != nil {
		return x.RepoId
	}
	return ""
}

func (x *AdvanceBranchRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AdvanceBranchRequest) GetCommitId() string {
	if x != nil {
		return x.CommitId
	}
	return ""
}

func (x *AdvanceBranchRequest) GetExpectedCommitId() string {
	if x != nil {
		return x.ExpectedCommitId
	}
	return ""
}

type DeleteBranchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepoId        string                 `protobuf:"bytes,1,opt,name=repo_id,json=repoId,proto3" json:"repo_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBranchRequest) Reset() {
	*x = DeleteBranchRequest{}
	mi := &file_verge_v1_branches_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBranchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBranchRequest) ProtoMessage() {}

func (x *DeleteBranchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_verge_v1_branches_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBranchRequest.ProtoReflect.Descriptor instead.
func (*DeleteBranchRequest) Descriptor() ([]byte, []int) {
	return file_verge_v1_branches_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteBranchRequest) GetRepoId() string {
	if x != nil {
		return x.RepoId
	}
	return ""
}

func (x *DeleteBranchRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteBranchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBranchResponse) Reset() {
	*x = DeleteBranchResponse{}
	mi := &file_verge_v1_branches_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBranchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBranchResponse) ProtoMessage() {}

func (x *DeleteBranchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_verge_v1_branches_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBranchResponse.ProtoReflect.Descriptor instead.
func (*DeleteBranchResponse) Descriptor() ([]byte, []int) {
	return file_verge_v1_branches_proto_rawDescGZIP(), []int{7}
}

var File_verge_v1_branches_proto protoreflect.FileDescriptor

const file_verge_v1_branches_proto_rawDesc = "" +
	"\n" +
	"\x17verge/v1/branches.proto\x12\bverge.v1\"q\n" +
	"\x06Branch\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x17\n" +
	"\arepo_id\x18\x02 \x01(\tR\x06repoId\x12\x1b\n" +
	"\tcommit_id\x18\x03 \x01(\tR\bcommitId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\"l\n" +
	"\x13CreateBranchRequest\x12\x17\n" +
	"\arepo_id\x18\x01 \x01(\tR\x06repoId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12(\n" +
	"\x10source_commit_id\x18\x03 \x01(\tR\x0esourceCommitId\"?\n" +
	"\x10GetBranchRequest\x12\x17\n" +
	"\arepo_id\x18\x01 \x01(\tR\x06repoId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\\\n" +
	"\x13ListBranchesRequest\x12\x17\n" +
	"\arepo_id\x18\x01 \x01(\tR\x06repoId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\tR\x06cursor\"e\n" +
	"\x14ListBranchesResponse\x12,\n" +
	"\bbranches\x18\x01 \x03(\v2\x10.verge.v1.BranchR\bbranches\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\"\x8e\x01\n" +
	"\x14AdvanceBranchRequest\x12\x17\n" +
	"\arepo_id\x18\x01 \x01(\tR\x06repoId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tcommit_id\x18\x03 \x01(\tR\bcommitId\x12,\n" +
	"\x12expected_commit_id\x18\x04 \x01(\tR\x10expectedCommitId\"B\n" +
	"\x13DeleteBranchRequest\x12\x17\n" +
	"\arepo_id\x18\x01 \x01(\tR\x06repoId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x16\n" +
	"\x14DeleteBranchResponse2\xec\x02\n" +
	"\rBranchService\x12?\n" +
	"\fCreateBranch\x12\x1d.verge.v1.CreateBranchRequest\x1a\x10.verge.v1.Branch\x129\n" +
	"\tGetBranch\x12\x1a.verge.v1.GetBranchRequest\x1a\x10.verge.v1.Branch\x12M\n" +
	"\fListBranches\x12\x1d.verge.v1.ListBranchesRequest\x1a\x1e.verge.v1.ListBranchesResponse\x12A\n" +
	"\rAdvanceBranch\x12\x1e.verge.v1.AdvanceBranchRequest\x1a\x10.verge.v1.Branch\x12M\n" +
	"\fDeleteBranch\x12\x1d.verge.v1.DeleteBranchRequest\x1a\x1e.verge.v1.DeleteBranchResponseB6Z4github.com/bhpcv252/verge/api/proto/verge/v1;vergev1b\x06proto3"

var (
	file_verge_v1_branches_proto_rawDescOnce sync.Once
	file_verge_v1_branches_proto_rawDescData []byte
)

func file_verge_v1_branches_proto_rawDescGZIP() []byte {
	file_verge_v1_branches_proto_rawDescOnce.Do(func() {
		file_verge_v1_branches_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_verge_v1_branches_proto_rawDesc), len(file_verge_v1_branches_proto_rawDesc)))
	})
	return file_verge_v1_branches_proto_rawDescData
}

var file_verge_v1_branches_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_verge_v1_branches_proto_goTypes = []any{
	(*Branch)(nil),               // 0: verge.v1.Branch
	(*CreateBranchRequest)(nil),  // 1: verge.v1.CreateBranchRequest
	(*GetBranchRequest)(nil),     // 2: verge.v1.GetBranchRequest
	(*ListBranchesRequest)(nil),  // 3: verge.v1.ListBranchesRequest
	(*ListBranchesResponse)(nil), // 4: verge.v1.ListBranchesResponse
	(*AdvanceBranchRequest)(nil), // 5: verge.v1.AdvanceBranchRequest
	(*DeleteBranchRequest)(nil),  // 6: verge.v1.DeleteBranchRequest
	(*DeleteBranchResponse)(nil), // 7: verge.v1.DeleteBranchResponse
}
var file_verge_v1_branches_proto_depIdxs = []int32{
	0, // 0: verge.v1.ListBranchesResponse.branches:type_name -> verge.v1.Branch
	1, // 1: verge.v1.BranchService.CreateBranch:input_type -> verge.v1.CreateBranchRequest
	2, // 2: verge.v1.BranchService.GetBranch:input_type -> verge.v1.GetBranchRequest
	3, // 3: verge.v1.BranchService.ListBranches:input_type -> verge.v1.ListBranchesRequest
	5, // 4: verge.v1.BranchService.AdvanceBranch:input_type -> verge.v1.AdvanceBranchRequest
	6, // 5: verge.v1.BranchService.DeleteBranch:input_type -> verge.v1.DeleteBranchRequest
	0, // 6: verge.v1.BranchService.CreateBranch:output_type -> verge.v1.Branch
	0, // 7: verge.v1.BranchService.GetBranch:output_type -> verge.v1.Branch
	4, // 8: verge.v1.BranchService.ListBranches:output_type -> verge.v1.ListBranchesResponse
	0, // 9: verge.v1.BranchService.AdvanceBranch:output_type -> verge.v1.Branch
	7, // 10: verge.v1.BranchService.DeleteBranch:output_type -> verge.v1.DeleteBranchResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_verge_v1_branches_proto_init() }
func file_verge_v1_branches_proto_init() {
	if File_verge_v1_branches_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_verge_v1_branches_proto_rawDesc), len(file_verge_v1_branches_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_verge_v1_branches_proto_goTypes,
		DependencyIndexes: file_verge_v1_branches_proto_depIdxs,
		MessageInfos:      file_verge_v1_branches_proto_msgTypes,
	}.Build()
	File_verge_v1_branches_proto = out.File
	file_verge_v1_branches_proto_goTypes = nil
	file_verge_v1_branches_proto_depIdxs = nil
}
