// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: verge/v1/common.proto

package vergev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataPointer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // "s3" | "url" | "db" | "custom"
	Location      string                 `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	Hash          string                 `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`         // optional - "sha256:..."
	Metadata      []byte                 `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"` // optional - raw JSON bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataPointer) Reset() {
	*x = DataPointer{}
	mi := &file_verge_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataPointer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataPointer) ProtoMessage() {}

func (x *DataPointer) ProtoReflect() protoreflect.Message {
	mi := &file_verge_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataPointer.ProtoReflect.Descriptor instead.
func (*DataPointer) Descriptor() ([]byte, []int) {
	return file_verge_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *DataPointer) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DataPointer) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *DataPointer) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *DataPointer) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type Commit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RepoId        string                 `protobuf:"bytes,2,opt,name=repo_id,json=repoId,proto3" json:"repo_id,omitempty"`
	ParentIds     []string               `protobuf:"bytes,3,rep,name=parent_ids,json=parentIds,proto3" json:"parent_ids,omitempty"`
	DataPointer   *DataPointer           `protobuf:"bytes,4,opt,name=data_pointer,json=dataPointer,proto3" json:"data_pointer,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Author        string                 `protobuf:"bytes,6,opt,name=author,proto3" json:"author,omitempty"`
	Timestamp     string                 `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // ISO 8601
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Commit) Reset() {
	*x = Commit{}
	mi := &file_verge_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Commit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Commit) ProtoMessage() {}

func (x *Commit) ProtoReflect() protoreflect.Message {
	mi := &file_verge_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Commit.ProtoReflect.Descriptor instead.
func (*Commit) Descriptor() ([]byte, []int) {
	return file_verge_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *Commit) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Commit) GetRepoId() string {
	if x != nil {
		return x.RepoId
	}
	return ""
}

func (x *Commit) GetParentIds() []string {
	if x != nil {
		return x.ParentIds
	}
	return nil
}

func (x *Commit) GetDataPointer() *DataPointer {
	if x != nil {
		return x.DataPointer
	}
	return nil
}

func (x *Commit) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Commit) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Commit) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

var File_verge_v1_common_proto protoreflect.FileDescriptor

const file_verge_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x15verge/v1/common.proto\x12\bverge.v1\"m\n" +
	"\vDataPointer\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1a\n" +
	"\blocation\x18\x02 \x01(\tR\blocation\x12\x12\n" +
	"\x04hash\x18\x03 \x01(\tR\x04hash\x12\x1a\n" +
	"\bmetadata\x18\x04 \x01(\fR\bmetadata\"\xda\x01\n" +
	"\x06Commit\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\arepo_id\x18\x02 \x01(\tR\x06repoId\x12\x1d\n" +
	"\n" +
	"parent_ids\x18\x03 \x03(\tR\tparentIds\x128\n" +
	"\fdata_pointer\x18\x04 \x01(\v2\x15.verge.v1.DataPointerR\vdataPointer\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x16\n" +
	"\x06author\x18\x06 \x01(\tR\x06author\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\tR\ttimestampB6Z4github.com/bhpcv252/verge/api/proto/verge/v1;vergev1b\x06proto3"

var (
	file_verge_v1_common_proto_rawDescOnce sync.Once
	file_verge_v1_common_proto_rawDescData []byte
)

func file_verge_v1_common_proto_rawDescGZIP() []byte {
	file_verge_v1_common_proto_rawDescOnce.Do(func() {
		file_verge_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_verge_v1_common_proto_rawDesc), len(file_verge_v1_common_proto_rawDesc)))
	})
	return file_verge_v1_common_proto_rawDescData
}

var file_verge_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_verge_v1_common_proto_goTypes = []any{
	(*DataPointer)(nil), // 0: verge.v1.DataPointer
	(*Commit)(nil),      // 1: verge.v1.Commit
}
var file_verge_v1_common_proto_depIdxs = []int32{
	0, // 0: verge.v1.Commit.data_pointer:type_name -> verge.v1.DataPointer
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_verge_v1_common_proto_init() }
func file_verge_v1_common_proto_init() {
	if File_verge_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_verge_v1_common_proto_rawDesc), len(file_verge_v1_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_verge_v1_common_proto_goTypes,
		DependencyIndexes: file_verge_v1_common_proto_depIdxs,
		MessageInfos:      file_verge_v1_common_proto_msgTypes,
	}.Build()
	File_verge_v1_common_proto = out.File
	file_verge_v1_common_proto_goTypes = nil
	file_verge_v1_common_proto_depIdxs = nil
}
