// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: verge/v1/commits.proto

package vergev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateCommitRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RepoId         string                 `protobuf:"bytes,1,opt,name=repo_id,json=repoId,proto3" json:"repo_id,omitempty"`
	ParentIds      []string               `protobuf:"bytes,2,rep,name=parent_ids,json=parentIds,proto3" json:"parent_ids,omitempty"`
	DataPointer    *DataPointer           `protobuf:"bytes,3,opt,name=data_pointer,json=dataPointer,proto3" json:"data_pointer,omitempty"`
	Message        string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Author         string                 `protobuf:"bytes,5,opt,name=author,proto3" json:"author,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,6,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"` // optional - client-generated UUID
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateCommitRequest) Reset() {
	*x = CreateCommitRequest{}
	mi := &file_verge_v1_commits_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommitRequest) ProtoMessage() {}

func (x *CreateCommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_verge_v1_commits_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommitRequest.ProtoReflect.Descriptor instead.
func (*CreateCommitRequest) Descriptor() ([]byte, []int) {
	return file_verge_v1_commits_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCommitRequest) GetRepoId() string {
	if x != nil {
		return x.RepoId
	}
	return ""
}

func (x *CreateCommitRequest) GetParentIds() []string {
	if x != nil {
		return x.ParentIds
	}
	return nil
}

func (x *CreateCommitRequest) GetDataPointer() *DataPointer {
	if x != nil {
		return x.DataPointer
	}
	return nil
}

func (x *CreateCommitRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateCommitRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *CreateCommitRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type CreateCommitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commit        *Commit                `protobuf:"bytes,1,opt,name=commit,proto3" json:"commit,omitempty"`
	Existing      bool                   `protobuf:"varint,2,opt,name=existing,proto3" json:"existing,omitempty"` // true if idempotency_key matched an existing commit
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommitResponse) Reset() {
	*x = CreateCommitResponse{}
	mi := &file_verge_v1_commits_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommitResponse) ProtoMessage() {}

func (x *CreateCommitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_verge_v1_commits_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommitResponse.ProtoReflect.Descriptor instead.
func (*CreateCommitResponse) Descriptor() ([]byte, []int) {
	return file_verge_v1_commits_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCommitResponse) GetCommit() *Commit {
	if x != nil {
		return x.Commit
	}
	return nil
}

func (x *CreateCommitResponse) GetExisting() bool {
	if x != nil {
		return x.Existing
	}
	return false
}

type GetCommitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepoId        string                 `protobuf:"bytes,1,opt,name=repo_id,json=repoId,proto3" json:"repo_id,omitempty"`
	CommitId      string                 `protobuf:"bytes,2,opt,name=commit_id,json=commitId,proto3" json:"commit_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommitRequest) Reset() {
	*x = GetCommitRequest{}
	mi := &file_verge_v1_commits_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommitRequest) ProtoMessage() {}

func (x *GetCommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_verge_v1_commits_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommitRequest.ProtoReflect.Descriptor instead.
func (*GetCommitRequest) Descriptor() ([]byte, []int) {
	return file_verge_v1_commits_proto_rawDescGZIP(), []int{2}
}

func (x *GetCommitRequest) GetRepoId() string {
	if x != nil {
		return x.RepoId
	}
	return ""
}

func (x *GetCommitRequest) GetCommitId() string {
	if x != nil {
		return x.CommitId
	}
	return ""
}

type ListCommitsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepoId        string                 `protobuf:"bytes,1,opt,name=repo_id,json=repoId,proto3" json:"repo_id,omitempty"`
	Branch        string                 `protobuf:"bytes,2,opt,name=branch,proto3" json:"branch,omitempty"`
	Author        string                 `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Since         string                 `protobuf:"bytes,4,opt,name=since,proto3" json:"since,omitempty"`         // ISO 8601
	Until         string                 `protobuf:"bytes,5,opt,name=until,proto3" json:"until,omitempty"`         // ISO 8601
	Traversal     string                 `protobuf:"bytes,6,opt,name=traversal,proto3" json:"traversal,omitempty"` // "flat" | "dag"
	Limit         int32                  `protobuf:"varint,7,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        string                 `protobuf:"bytes,8,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommitsRequest) Reset() {
	*x = ListCommitsRequest{}
	mi := &file_verge_v1_commits_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommitsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommitsRequest) ProtoMessage() {}

func (x *ListCommitsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_verge_v1_commits_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommitsRequest.ProtoReflect.Descriptor instead.
func (*ListCommitsRequest) Descriptor() ([]byte, []int) {
	return file_verge_v1_commits_proto_rawDescGZIP(), []int{3}
}

func (x *ListCommitsRequest) GetRepoId() string {
	if x != nil {
		return x.RepoId
	}
	return ""
}

func (x *ListCommitsRequest) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *ListCommitsRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *ListCommitsRequest) GetSince() string {
	if x != nil {
		return x.Since
	}
	return ""
}

func (x *ListCommitsRequest) GetUntil() string {
	if x != nil {
		return x.Until
	}
	return ""
}

func (x *ListCommitsRequest) GetTraversal() string {
	if x != nil {
		return x.Traversal
	}
	return ""
}

func (x *ListCommitsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListCommitsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type ListCommitsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commits       []*Commit              `protobuf:"bytes,1,rep,name=commits,proto3" json:"commits,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommitsResponse) Reset() {
	*x = ListCommitsResponse{}
	mi := &file_verge_v1_commits_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommitsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommitsResponse) ProtoMessage() {}

func (x *ListCommitsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_verge_v1_commits_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommitsResponse.ProtoReflect.Descriptor instead.
func (*ListCommitsResponse) Descriptor() ([]byte, []int) {
	return file_verge_v1_commits_proto_rawDescGZIP(), []int{4}
}

func (x *ListCommitsResponse) GetCommits() []*Commit {
	if x != nil {
		return x.Commits
	}
	return nil
}

func (x *ListCommitsResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

type GetParentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepoId        string                 `protobuf:"bytes,1,opt,name=repo_id,json=repoId,proto3" json:"repo_id,omitempty"`
	CommitId      string                 `protobuf:"bytes,2,opt,name=commit_id,json=commitId,proto3" json:"commit_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetParentsRequest) Reset() {
	*x = GetParentsRequest{}
	mi := &file_verge_v1_commits_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetParentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParentsRequest) ProtoMessage() {}

func (x *GetParentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_verge_v1_commits_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParentsRequest.ProtoReflect.Descriptor instead.
func (*GetParentsRequest) Descriptor() ([]byte, []int) {
	return file_verge_v1_commits_proto_rawDescGZIP(), []int{5}
}

func (x *GetParentsRequest) GetRepoId() string {
	if x != nil {
		return x.RepoId
	}
	return ""
}

func (x *GetParentsRequest) GetCommitId() string {
	if x != nil {
		return x.CommitId
	}
	return ""
}

type GetParentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommitId      string                 `protobuf:"bytes,1,opt,name=commit_id,json=commitId,proto3" json:"commit_id,omitempty"`
	Parents       []*Commit              `protobuf:"bytes,2,rep,name=parents,proto3" json:"parents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetParentsResponse) Reset() {
	*x = GetParentsResponse{}
	mi := &file_verge_v1_commits_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetParentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParentsResponse) ProtoMessage() {}

func (x *GetParentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_verge_v1_commits_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParentsResponse.ProtoReflect.Descriptor instead.
func (*GetParentsResponse) Descriptor() ([]byte, []int) {
	return file_verge_v1_commits_proto_rawDescGZIP(), []int{6}
}

func (x *GetParentsResponse) GetCommitId() string {
	if x != nil {
		return x.CommitId
	}
	return ""
}

func (x *GetParentsResponse) GetParents() []*Commit {
	if x != nil {
		return x.Parents
	}
	return nil
}

var File_verge_v1_commits_proto protoreflect.FileDescriptor

const file_verge_v1_commits_proto_rawDesc = "" +
	"\n" +
	"\x16verge/v1/commits.proto\x12\bverge.v1\x1a\x15verge/v1/common.proto\"\xe2\x01\n" +
	"\x13CreateCommitRequest\x12\x17\n" +
	"\arepo_id\x18\x01 \x01(\tR\x06repoId\x12\x1d\n" +
	"\n" +
	"parent_ids\x18\x02 \x03(\tR\tparentIds\x128\n" +
	"\fdata_pointer\x18\x03 \x01(\v2\x15.verge.v1.DataPointerR\vdataPointer\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x16\n" +
	"\x06author\x18\x05 \x01(\tR\x06author\x12'\n" +
	"\x0fidempotency_key\x18\x06 \x01(\tR\x0eidempotencyKey\"\\\n" +
	"\x14CreateCommitResponse\x12(\n" +
	"\x06commit\x18\x01 \x01(\v2\x10.verge.v1.CommitR\x06commit\x12\x1a\n" +
	"\bexisting\x18\x02 \x01(\bR\bexisting\"H\n" +
	"\x10GetCommitRequest\x12\x17\n" +
	"\arepo_id\x18\x01 \x01(\tR\x06repoId\x12\x1b\n" +
	"\tcommit_id\x18\x02 \x01(\tR\bcommitId\"\xd5\x01\n" +
	"\x12ListCommitsRequest\x12\x17\n" +
	"\arepo_id\x18\x01 \x01(\tR\x06repoId\x12\x16\n" +
	"\x06branch\x18\x02 \x01(\tR\x06branch\x12\x16\n" +
	"\x06author\x18\x03 \x01(\tR\x06author\x12\x14\n" +
	"\x05since\x18\x04 \x01(\tR\x05since\x12\x14\n" +
	"\x05until\x18\x05 \x01(\tR\x05until\x12\x1c\n" +
	"\ttraversal\x18\x06 \x01(\tR\ttraversal\x12\x14\n" +
	"\x05limit\x18\a \x01(\x05R\x05limit\x12\x16\n" +
	"\x06cursor\x18\b \x01(\tR\x06cursor\"b\n" +
	"\x13ListCommitsResponse\x12*\n" +
	"\acommits\x18\x01 \x03(\v2\x10.verge.v1.CommitR\acommits\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\"I\n" +
	"\x11GetParentsRequest\x12\x17\n" +
	"\arepo_id\x18\x01 \x01(\tR\x06repoId\x12\x1b\n" +
	"\tcommit_id\x18\x02 \x01(\tR\bcommitId\"]\n" +
	"\x12GetParentsResponse\x12\x1b\n" +
	"\tcommit_id\x18\x01 \x01(\tR\bcommitId\x12*\n" +
	"\aparents\x18\x02 \x03(\v2\x10.verge.v1.CommitR\aparents2\xae\x02\n" +
	"\rCommitService\x12M\n" +
	"\fCreateCommit\x12\x1d.verge.v1.CreateCommitRequest\x1a\x1e.verge.v1.CreateCommitResponse\x129\n" +
	"\tGetCommit\x12\x1a.verge.v1.GetCommitRequest\x1a\x10.verge.v1.Commit\x12J\n" +
	"\vListCommits\x12\x1c.verge.v1.ListCommitsRequest\x1a\x1d.verge.v1.ListCommitsResponse\x12G\n" +
	"\n" +
	"GetParents\x12\x1b.verge.v1.GetParentsRequest\x1a\x1c.verge.v1.GetParentsResponseB6Z4github.com/bhpcv252/verge/api/proto/verge/v1;vergev1b\x06proto3"

var (
	file_verge_v1_commits_proto_rawDescOnce sync.Once
	file_verge_v1_commits_proto_rawDescData []byte
)

func file_verge_v1_commits_proto_rawDescGZIP() []byte {
	file_verge_v1_commits_proto_rawDescOnce.Do(func() {
		file_verge_v1_commits_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_verge_v1_commits_proto_rawDesc), len(file_verge_v1_commits_proto_rawDesc)))
	})
	return file_verge_v1_commits_proto_rawDescData
}

var file_verge_v1_commits_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_verge_v1_commits_proto_goTypes = []any{
	(*CreateCommitRequest)(nil),  // 0: verge.v1.CreateCommitRequest
	(*CreateCommitResponse)(nil), // 1: verge.v1.CreateCommitResponse
	(*GetCommitRequest)(nil),     // 2: verge.v1.GetCommitRequest
	(*ListCommitsRequest)(nil),   // 3: verge.v1.ListCommitsRequest
	(*ListCommitsResponse)(nil),  // 4: verge.v1.ListCommitsResponse
	(*GetParentsRequest)(nil),    // 5: verge.v1.GetParentsRequest
	(*GetParentsResponse)(nil),   // 6: verge.v1.GetParentsResponse
	(*DataPointer)(nil),          // 7: verge.v1.DataPointer
	(*Commit)(nil),               // 8: verge.v1.Commit
}
var file_verge_v1_commits_proto_depIdxs = []int32{
	7, // 0: verge.v1.CreateCommitRequest.data_pointer:type_name -> verge.v1.DataPointer
	8, // 1: verge.v1.CreateCommitResponse.commit:type_name -> verge.v1.Commit
	8, // 2: verge.v1.ListCommitsResponse.commits:type_name -> verge.v1.Commit
	8, // 3: verge.v1.GetParentsResponse.parents:type_name -> verge.v1.Commit
	0, // 4: verge.v1.CommitService.CreateCommit:input_type -> verge.v1.CreateCommitRequest
	2, // 5: verge.v1.CommitService.GetCommit:input_type -> verge.v1.GetCommitRequest
	3, // 6: verge.v1.CommitService.ListCommits:input_type -> verge.v1.ListCommitsRequest
	5, // 7: verge.v1.CommitService.GetParents:input_type -> verge.v1.GetParentsRequest
	1, // 8: verge.v1.CommitService.CreateCommit:output_type -> verge.v1.CreateCommitResponse
	8, // 9: verge.v1.CommitService.GetCommit:output_type -> verge.v1.Commit
	4, // 10: verge.v1.CommitService.ListCommits:output_type -> verge.v1.ListCommitsResponse
	6, // 11: verge.v1.CommitService.GetParents:output_type -> verge.v1.GetParentsResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_verge_v1_commits_proto_init() }
func file_verge_v1_commits_proto_init() {
	if File_verge_v1_commits_proto != nil {
		return
	}
	file_verge_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_verge_v1_commits_proto_rawDesc), len(file_verge_v1_commits_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_verge_v1_commits_proto_goTypes,
		DependencyIndexes: file_verge_v1_commits_proto_depIdxs,
		MessageInfos:      file_verge_v1_commits_proto_msgTypes,
	}.Build()
	File_verge_v1_commits_proto = out.File
	file_verge_v1_commits_proto_goTypes = nil
	file_verge_v1_commits_proto_depIdxs = nil
}
