// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: verge/v1/merges.proto

package vergev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MergeService_CreateMerge_FullMethodName = "/verge.v1.MergeService/CreateMerge"
)

// MergeServiceClient is the client API for MergeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MergeServiceClient interface {
	CreateMerge(ctx context.Context, in *CreateMergeRequest, opts ...grpc.CallOption) (*Commit, error)
}

type mergeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMergeServiceClient(cc grpc.ClientConnInterface) MergeServiceClient {
	return &mergeServiceClient{cc}
}

func (c *mergeServiceClient) CreateMerge(ctx context.Context, in *CreateMergeRequest, opts ...grpc.CallOption) (*Commit, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Commit)
	err := c.cc.Invoke(ctx, MergeService_CreateMerge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MergeServiceServer is the server API for MergeService service.
// All implementations must embed UnimplementedMergeServiceServer
// for forward compatibility.
type MergeServiceServer interface {
	CreateMerge(context.Context, *CreateMergeRequest) (*Commit, error)
	mustEmbedUnimplementedMergeServiceServer()
}

// UnimplementedMergeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMergeServiceServer struct{}

func (UnimplementedMergeServiceServer) CreateMerge(context.Context, *CreateMergeRequest) (*Commit, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateMerge not implemented")
}
func (UnimplementedMergeServiceServer) mustEmbedUnimplementedMergeServiceServer() {}
func (UnimplementedMergeServiceServer) testEmbeddedByValue()                      {}

// UnsafeMergeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MergeServiceServer will
// result in compilation errors.
type UnsafeMergeServiceServer interface {
	mustEmbedUnimplementedMergeServiceServer()
}

func RegisterMergeServiceServer(s grpc.ServiceRegistrar, srv MergeServiceServer) {
	// If the following call panics, it indicates UnimplementedMergeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MergeService_ServiceDesc, srv)
}

func _MergeService_CreateMerge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMergeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MergeServiceServer).CreateMerge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MergeService_CreateMerge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MergeServiceServer).CreateMerge(ctx, req.(*CreateMergeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MergeService_ServiceDesc is the grpc.ServiceDesc for MergeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MergeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "verge.v1.MergeService",
	HandlerType: (*MergeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateMerge",
			Handler:    _MergeService_CreateMerge_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "verge/v1/merges.proto",
}
