// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: verge/v1/merges.proto

package vergev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateMergeRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RepoId             string                 `protobuf:"bytes,1,opt,name=repo_id,json=repoId,proto3" json:"repo_id,omitempty"`
	ParentIds          []string               `protobuf:"bytes,2,rep,name=parent_ids,json=parentIds,proto3" json:"parent_ids,omitempty"`                              // exactly two
	ExpectedTargetHead string                 `protobuf:"bytes,3,opt,name=expected_target_head,json=expectedTargetHead,proto3" json:"expected_target_head,omitempty"` // required - optimistic lock
	TargetBranch       string                 `protobuf:"bytes,4,opt,name=target_branch,json=targetBranch,proto3" json:"target_branch,omitempty"`
	DataPointer        *DataPointer           `protobuf:"bytes,5,opt,name=data_pointer,json=dataPointer,proto3" json:"data_pointer,omitempty"`
	Message            string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	Author             string                 `protobuf:"bytes,7,opt,name=author,proto3" json:"author,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CreateMergeRequest) Reset() {
	*x = CreateMergeRequest{}
	mi := &file_verge_v1_merges_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMergeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMergeRequest) ProtoMessage() {}

func (x *CreateMergeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_verge_v1_merges_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMergeRequest.ProtoReflect.Descriptor instead.
func (*CreateMergeRequest) Descriptor() ([]byte, []int) {
	return file_verge_v1_merges_proto_rawDescGZIP(), []int{0}
}

func (x *CreateMergeRequest) GetRepoId() string {
	if x != nil {
		return x.RepoId
	}
	return ""
}

func (x *CreateMergeRequest) GetParentIds() []string {
	if x != nil {
		return x.ParentIds
	}
	return nil
}

func (x *CreateMergeRequest) GetExpectedTargetHead() string {
	if x != nil {
		return x.ExpectedTargetHead
	}
	return ""
}

func (x *CreateMergeRequest) GetTargetBranch() string {
	if x != nil {
		return x.TargetBranch
	}
	return ""
}

func (x *CreateMergeRequest) GetDataPointer() *DataPointer {
	if x != nil {
		return x.DataPointer
	}
	return nil
}

func (x *CreateMergeRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateMergeRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

var File_verge_v1_merges_proto protoreflect.FileDescriptor

const file_verge_v1_merges_proto_rawDesc = "" +
	"\n" +
	"\x15verge/v1/merges.proto\x12\bverge.v1\x1a\x15verge/v1/common.proto\"\x8f\x02\n" +
	"\x12CreateMergeRequest\x12\x17\n" +
	"\arepo_id\x18\x01 \x01(\tR\x06repoId\x12\x1d\n" +
	"\n" +
	"parent_ids\x18\x02 \x03(\tR\tparentIds\x120\n" +
	"\x14expected_target_head\x18\x03 \x01(\tR\x12expectedTargetHead\x12#\n" +
	"\rtarget_branch\x18\x04 \x01(\tR\ftargetBranch\x128\n" +
	"\fdata_pointer\x18\x05 \x01(\v2\x15.verge.v1.DataPointerR\vdataPointer\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\x12\x16\n" +
	"\x06author\x18\a \x01(\tR\x06author2M\n" +
	"\fMergeService\x12=\n" +
	"\vCreateMerge\x12\x1c.verge.v1.CreateMergeRequest\x1a\x10.verge.v1.CommitB6Z4github.com/bhpcv252/verge/api/proto/verge/v1;vergev1b\x06proto3"

var (
	file_verge_v1_merges_proto_rawDescOnce sync.Once
	file_verge_v1_merges_proto_rawDescData []byte
)

func file_verge_v1_merges_proto_rawDescGZIP() []byte {
	file_verge_v1_merges_proto_rawDescOnce.Do(func() {
		file_verge_v1_merges_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_verge_v1_merges_proto_rawDesc), len(file_verge_v1_merges_proto_rawDesc)))
	})
	return file_verge_v1_merges_proto_rawDescData
}

var file_verge_v1_merges_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_verge_v1_merges_proto_goTypes = []any{
	(*CreateMergeRequest)(nil), // 0: verge.v1.CreateMergeRequest
	(*DataPointer)(nil),        // 1: verge.v1.DataPointer
	(*Commit)(nil),             // 2: verge.v1.Commit
}
var file_verge_v1_merges_proto_depIdxs = []int32{
	1, // 0: verge.v1.CreateMergeRequest.data_pointer:type_name -> verge.v1.DataPointer
	0, // 1: verge.v1.MergeService.CreateMerge:input_type -> verge.v1.CreateMergeRequest
	2, // 2: verge.v1.MergeService.CreateMerge:output_type -> verge.v1.Commit
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_verge_v1_merges_proto_init() }
func file_verge_v1_merges_proto_init() {
	if File_verge_v1_merges_proto != nil {
		return
	}
	file_verge_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_verge_v1_merges_proto_rawDesc), len(file_verge_v1_merges_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_verge_v1_merges_proto_goTypes,
		DependencyIndexes: file_verge_v1_merges_proto_depIdxs,
		MessageInfos:      file_verge_v1_merges_proto_msgTypes,
	}.Build()
	File_verge_v1_merges_proto = out.File
	file_verge_v1_merges_proto_goTypes = nil
	file_verge_v1_merges_proto_depIdxs = nil
}
