// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: verge/v1/repos.proto

package vergev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Repository struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DefaultBranch string                 `protobuf:"bytes,3,opt,name=default_branch,json=defaultBranch,proto3" json:"default_branch,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // ISO 8601
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Repository) Reset() {
	*x = Repository{}
	mi := &file_verge_v1_repos_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Repository) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Repository) ProtoMessage() {}

func (x *Repository) ProtoReflect() protoreflect.Message {
	mi := &file_verge_v1_repos_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Repository.ProtoReflect.Descriptor instead.
func (*Repository) Descriptor() ([]byte, []int) {
	return file_verge_v1_repos_proto_rawDescGZIP(), []int{0}
}

func (x *Repository) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Repository) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Repository) GetDefaultBranch() string {
	if x != nil {
		return x.DefaultBranch
	}
	return ""
}

func (x *Repository) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type CreateRepoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DefaultBranch string                 `protobuf:"bytes,2,opt,name=default_branch,json=defaultBranch,proto3" json:"default_branch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRepoRequest) Reset() {
	*x = CreateRepoRequest{}
	mi := &file_verge_v1_repos_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRepoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRepoRequest) ProtoMessage() {}

func (x *CreateRepoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_verge_v1_repos_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRepoRequest.ProtoReflect.Descriptor instead.
func (*CreateRepoRequest) Descriptor() ([]byte, []int) {
	return file_verge_v1_repos_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRepoRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRepoRequest) GetDefaultBranch() string {
	if x != nil {
		return x.DefaultBranch
	}
	return ""
}

type GetRepoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepoId        string                 `protobuf:"bytes,1,opt,name=repo_id,json=repoId,proto3" json:"repo_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRepoRequest) Reset() {
	*x = GetRepoRequest{}
	mi := &file_verge_v1_repos_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRepoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRepoRequest) ProtoMessage() {}

func (x *GetRepoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_verge_v1_repos_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRepoRequest.ProtoReflect.Descriptor instead.
func (*GetRepoRequest) Descriptor() ([]byte, []int) {
	return file_verge_v1_repos_proto_rawDescGZIP(), []int{2}
}

func (x *GetRepoRequest) GetRepoId() string {
	if x != nil {
		return x.RepoId
	}
	return ""
}

type ListReposRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        string                 `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReposRequest) Reset() {
	*x = ListReposRequest{}
	mi := &file_verge_v1_repos_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReposRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReposRequest) ProtoMessage() {}

func (x *ListReposRequest) ProtoReflect() protoreflect.Message {
	mi := &file_verge_v1_repos_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReposRequest.ProtoReflect.Descriptor instead.
func (*ListReposRequest) Descriptor() ([]byte, []int) {
	return file_verge_v1_repos_proto_rawDescGZIP(), []int{3}
}

func (x *ListReposRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListReposRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type ListReposResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repos         []*Repository          `protobuf:"bytes,1,rep,name=repos,proto3" json:"repos,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"` // empty string when no more pages
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReposResponse) Reset() {
	*x = ListReposResponse{}
	mi := &file_verge_v1_repos_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReposResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReposResponse) ProtoMessage() {}

func (x *ListReposResponse) ProtoReflect() protoreflect.Message {
	mi := &file_verge_v1_repos_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReposResponse.ProtoReflect.Descriptor instead.
func (*ListReposResponse) Descriptor() ([]byte, []int) {
	return file_verge_v1_repos_proto_rawDescGZIP(), []int{4}
}

func (x *ListReposResponse) GetRepos() []*Repository {
	if x != nil {
		return x.Repos
	}
	return nil
}

func (x *ListReposResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

var File_verge_v1_repos_proto protoreflect.FileDescriptor

const file_verge_v1_repos_proto_rawDesc = "" +
	"\n" +
	"\x14verge/v1/repos.proto\x12\bverge.v1\"v\n" +
	"\n" +
	"Repository\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\x0edefault_branch\x18\x03 \x01(\tR\rdefaultBranch\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\"N\n" +
	"\x11CreateRepoRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x0edefault_branch\x18\x02 \x01(\tR\rdefaultBranch\")\n" +
	"\x0eGetRepoRequest\x12\x17\n" +
	"\arepo_id\x18\x01 \x01(\tR\x06repoId\"@\n" +
	"\x10ListReposRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\"`\n" +
	"\x11ListReposResponse\x12*\n" +
	"\x05repos\x18\x01 \x03(\v2\x14.verge.v1.RepositoryR\x05repos\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor2\xd5\x01\n" +
	"\x11RepositoryService\x12?\n" +
	"\n" +
	"CreateRepo\x12\x1b.verge.v1.CreateRepoRequest\x1a\x14.verge.v1.Repository\x129\n" +
	"\aGetRepo\x12\x18.verge.v1.GetRepoRequest\x1a\x14.verge.v1.Repository\x12D\n" +
	"\tListRepos\x12\x1a.verge.v1.ListReposRequest\x1a\x1b.verge.v1.ListReposResponseB6Z4github.com/bhpcv252/verge/api/proto/verge/v1;vergev1b\x06proto3"

var (
	file_verge_v1_repos_proto_rawDescOnce sync.Once
	file_verge_v1_repos_proto_rawDescData []byte
)

func file_verge_v1_repos_proto_rawDescGZIP() []byte {
	file_verge_v1_repos_proto_rawDescOnce.Do(func() {
		file_verge_v1_repos_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_verge_v1_repos_proto_rawDesc), len(file_verge_v1_repos_proto_rawDesc)))
	})
	return file_verge_v1_repos_proto_rawDescData
}

var file_verge_v1_repos_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_verge_v1_repos_proto_goTypes = []any{
	(*Repository)(nil),        // 0: verge.v1.Repository
	(*CreateRepoRequest)(nil), // 1: verge.v1.CreateRepoRequest
	(*GetRepoRequest)(nil),    // 2: verge.v1.GetRepoRequest
	(*ListReposRequest)(nil),  // 3: verge.v1.ListReposRequest
	(*ListReposResponse)(nil), // 4: verge.v1.ListReposResponse
}
var file_verge_v1_repos_proto_depIdxs = []int32{
	0, // 0: verge.v1.ListReposResponse.repos:type_name -> verge.v1.Repository
	1, // 1: verge.v1.RepositoryService.CreateRepo:input_type -> verge.v1.CreateRepoRequest
	2, // 2: verge.v1.RepositoryService.GetRepo:input_type -> verge.v1.GetRepoRequest
	3, // 3: verge.v1.RepositoryService.ListRepos:input_type -> verge.v1.ListReposRequest
	0, // 4: verge.v1.RepositoryService.CreateRepo:output_type -> verge.v1.Repository
	0, // 5: verge.v1.RepositoryService.GetRepo:output_type -> verge.v1.Repository
	4, // 6: verge.v1.RepositoryService.ListRepos:output_type -> verge.v1.ListReposResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_verge_v1_repos_proto_init() }
func file_verge_v1_repos_proto_init() {
	if File_verge_v1_repos_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_verge_v1_repos_proto_rawDesc), len(file_verge_v1_repos_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_verge_v1_repos_proto_goTypes,
		DependencyIndexes: file_verge_v1_repos_proto_depIdxs,
		MessageInfos:      file_verge_v1_repos_proto_msgTypes,
	}.Build()
	File_verge_v1_repos_proto = out.File
	file_verge_v1_repos_proto_goTypes = nil
	file_verge_v1_repos_proto_depIdxs = nil
}
