FROM golang:1.25-alpine

RUN apk add --no-cache git bash curl

# Install migrate
RUN go install -tags 'postgres' \
    github.com/golang-migrate/migrate/v4/cmd/migrate@v4.19.1

# Install buf
RUN go install github.com/bufbuild/buf/cmd/buf@v1.69.0

# Install protoc plugins
RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.36.11
RUN go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.6.2

# Install linter
RUN go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.64.8

ENV PATH="/go/bin:${PATH}"

WORKDIR /workspace
